{% set name = "phidl" %}
{% set version = "1.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/phidl-{{ version }}.tar.gz
  sha256: 828d9bbcdc1250a53e47224add3dcb1c189f9621af8e7bccede96322d5c98601

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - gdspy >=1.5
    - matplotlib-base
    - numpy
    - python >=3.7
    - six

test:
  imports:
    - phidl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/phidl/
  doc_url: https://phidl.readthedocs.io/en/latest/tutorials.html
  summary: PHIDL
  license: MIT
  # License file manually packaged. See https://github.com/amccaugh/phidl/pull/86
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joamatab
