{% set name = "phidl" %}
{% set version = "1.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/phidl-{{ version }}.tar.gz
  sha256: 40c10a46b6b8b6a316d86b8a22123e4c0ab4a0909c4851aed5d1f138218d96b0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - gdspy >=1.5
    - matplotlib-base
    - numpy
    - python >=3.7
    - six

test:
  imports:
    - phidl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/phidl/
  doc_url: https://phidl.readthedocs.io/en/latest/tutorials.html
  summary: PHIDL
  license: MIT
  # License file manually packaged. See https://github.com/amccaugh/phidl/pull/86
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joamatab
